apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qf2usfk55-go
  janus-idp.io/tekton: qf2usfk55-go
  backstage.io/kubernetes-id: qf2usfk55-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qf2usfk55-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
